### ISSUE TITLE
Make get fails due to inaccessible repository

### ISSUE THREAD

**Issue by dustinkerstein** [lanikai/alohartc#118]
When I run `make get` I see this error:

```
go: github.com/lanikai/oahu/api@v0.0.0-20190703205954-e5008c1038bd: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/pi/go/pkg/mod/cache/vcs/5cbe38e991ccac88249047428b47b8194a6f5523d3834d62b1e7ea0b64628b17: exit status 128:
	remote: Repository not found.
	fatal: repository 'https://github.com/lanikai/oahu/' not found
go: error loading module requirements
make: *** [Makefile:13: get] Error 1
```

And I confirmed that https://github.com/lanikai/oahu/ no long exists or is now private. Would it be possible to fix this? Thanks!

**Comment by hiszpanski** [comment]
Good catch. To add some context around this, AlohaRTC was developed by Lanikai Labs. The team joined Verkada earlier this year. As part of the transition, we opened sourced AlohaRTC (WebRTC stack for IoT devices), but not Oahu (signaling service). We're not able to provide on-going support for the project, but open sourced it in hopes that it would be of value to the community. Recommend forking the project and replacing references to `oahu` with your own signaling solution.
